### ISSUE TITLE
TransactionListActivity

### ISSUE THREAD

**Issue by classictoni** [fstreun/PayApp#18]
when clicking on a user in the GroupActivty or Options->showAllTransactions a list of transactions should appear

**Comment by classictoni** [comment]
starting now

**Comment by classictoni** [comment]
I implemented it in the same way as GroupActivity but unfortunately it crashes when getting the convertView in the ListTransactionAdapter :(
pushed it on antonbr3
@fstreun chasches mal aluege?

**Comment by fstreun** [comment]
@abruch666 : crash fixed

**Comment by classictoni** [comment]
done
(a few non-necessary todos left)
